### ISSUE TITLE
Setup rClone with service account https://rclone.org/drive/#service-account-support

### ISSUE THREAD

**Issue by jt14den** [ucla-data-science-center/dataverse-ansible#89]

**Comment by jmjamison** [comment]
Request service account for dataverse@library.ucla.edu,  https://jira.library.ucla.edu/browse/AJ-2416

**Comment by jt14den** [comment]
https://rclone.org/drive/#service-account-support

**Comment by jmjamison** [comment]
I can create an api-key for a service account,  but I'm trying to figure out how to restrict it.

**Comment by jmjamison** [comment]
Created a service account, 'dataverse', from datascience@g.ucla.edu account.

**Comment by jt14den** [comment]
IS this issue closed?

**Comment by jt14den** [comment]
I should be able to log into dvn productino to see how its set up.

**Comment by jt14den** [comment]
@jt14den needs to backtrack on how to set up service account.
